openapi: '3.0.0'
info:
  version: 1.0.0
  title: AÃ©roclub Air France - Toulouse API
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /flights:
    get:
      summary: List all flights
      operationId: listFlights
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of flights
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flights'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a flight
      operationId: createFlight
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /flights/{flightId}:
    get:
      summary: Info for a flight
      operationId: showFlightById
      parameters:
        - name: flightId
          in: path
          required: true
          description: The id of the flight to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flights'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /aircraft:
    get:
      summary: List all aircraft
      operationId: listAircraft
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of aircraft
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AircraftList'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Add aircraft
      operationId: createAircraft
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /aircraft/{aircraftId}:
    get:
      summary: Info for aircraft
      operationId: showAircraftById
      parameters:
        - name: aircraftId
          in: path
          required: true
          description: The id of the aircraft to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AircraftList'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Flight:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        destination:
          type: string
    Flights:
      type: array
      items:
        $ref: '#/components/schemas/Flight'
    Aircraft:
      required:
        - id
        - model
      properties:
        id:
          type: integer
          format: int64
        model:
          type: string
        registration:
          type: string
    AircraftList:
      type: array
      items:
        $ref: '#/components/schemas/Aircraft'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string